### ISSUE TITLE
Undetected?

### ISSUE THREAD

**Issue by GainoSaurus** [kagurazakasanae/Mhyprot2DrvControl#1]
Is this driver undected? Can it be used to bypass Anti cheats? Does it do function hooking or does it use shared memory? Thanks in Advance

**Comment by kagurazakasanae** [comment]
not tested, it may be used to bypass for now but it has many detect vectors so it's not a good choice for this case. it do have function hooking to protect the process that call it and it uses mdl to rw memory, all of these can be detected and signed by ac.
