### ISSUE TITLE
demo的读内存有问题

### ISSUE THREAD

**Issue by xiaonian233** [kagurazakasanae/Mhyprot2DrvControl#3]
软件为release 64位版本
![Snipaste_2021-10-09_23-51-41](https://user-images.githubusercontent.com/21072615/136665523-7e2244ef-ddf0-434f-a4ab-5fb415b64d47.png)
电脑版本是：20H2（19042.985）

**Comment by kagurazakasanae** [comment]
vs编译时选择x64
