### ISSUE TITLE
[HELP] About Mhy New Driver

### ISSUE THREAD

**Issue by AliceCode987** [kagurazakasanae/Mhyprot2DrvControl#4]
Hello, mhy recently updated drivers, joined the mhypbase.dll , the DLL is said to be loaded mhyprot2. Sys, mhyprot3. Sys

1.Do you plan to reverse drive 3 and Base DLL files?
2.As far as you know, is the function of driver 2 limited to (kill process, read and write memory, enumerate process module) these three functions?
3.Does the Driver Code of DeviceIoControl have other functions?
4.Does the MHY driver have any other behaviors/functions?

Thank you very much for your reply!

**Comment by kagurazakasanae** [comment]
1. No
2. basiclly, it can also read/write kernel memory, please have a look at some other repo on github.
3. each iocontrol code refer to different function, just drag file into IDA and check.
4. from whay I know the driver will just perform the command that you requested via iocontrol, it will not perform any other behaviors by itself.
